import { Departement } from "./departement";
import { Groupe } from "./groupe";
import { Role } from "./role";

export class Collaborateur {
    uuid!: string;
    photo!: string;
    role!: Role;
    nom!: string;
    prenom!: string;
    adresse_personnelle!: string;
    email!: string;
    telephone!: string;
    identification_nationale!: string;
    numero_securite_sociale!: string;
    rib!: string;
    date_naissance!: string;
    situation!: string;
    nombre_enfants!: number;
    nationalite!: string;
    niveau_etudes!: string;
    diplomes!: Array<any>;
    competences!: Array<any>;
    langues!: Array<any>;
    certifications!: Array<any>;
    avantages!: Array<any>;
    statut!: boolean;
    fonction!: string;
    nombre_jours_conge!: number;
    salaire_de_base!: number;
    matricule!: string;
    commentaire!: string;
    groupe!: Groupe;
    departement!: Departement;
    superviseur!: Collaborateur;
    subordonnes!: Array<Collaborateur>;
    experiences_antierieurs!: Array<string>;
    // contrat!: Collaborateur;
    // salaires!: Collaborateur;
    // salaireActuel!: Collaborateur;
    // primes!: Collaborateur;
    // conges!: Collaborateur;
    // soldeCoges!: Collaborateur;
    created_at!: string;
}
