import { Docteur } from "./docteur";
import { MedicalHistorique } from "./medical-historique";
import { Patient } from "./patient";

export class Consultation {
    id!: string;
    analyseComments!: string;
    analyseConsultations!: Array<any>;
    anamnesis!: string;
    attachements!: Array<any>;
    chiefComplaintConsultations!: Array<any>;
    comment!: string;
    conclusion!: string;
    createdAt!: string;
    doctor!: Docteur;
    doctorId!: string;
    endTime!: string;
    exitMode!: string;
    imagingComments!: string;
    imagingConsultations!: Array<any>;
    isLocal!: boolean;
    lastTimeDuration!: string;
    medicalHistoryId!: string;
    medicalHistory!: MedicalHistorique;
    medicationComments!: string;
    medicationConsultations!: Array<any>;
    motifComplaint!: Array<any>;
    nextAppointementId!: string;
    paraclinicalExamination!: string;
    patientId!: string;
    patient!: Patient;
    riskFactors!: Array<any>;
    specialistConclusion!: string;
    startTime!: string;
    state!: string;
    stationId!: string;
    steps!: Array<any>;
    updatedAt!: string;
    userId!: string;
    currentStep!: string;
}
